# Generated by Django 6.0.1 on 2026-06-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_boo_facilit_1dc6bd_idx',
            old_name='booking_facilit_724ed1_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_boo_custome_954457_idx',
            old_name='booking_custome_8fed7a_idx',
        ),
    ]
